### ISSUE TITLE
RelativePortal unit testing .

### ISSUE THREAD

**Issue by raku1089** [sunify/react-relative-portal#20]
can any one suggest how to write unit test for RelativePortal.
challenge - unable to find component or any html tags  written inside RelativePortal.
```<RelativePortal  component="div" >  <div><OtherComponent/></div> </RelativePortal> ```
test : 
```const wrapper =mount(<MyComponent />); wrapper.find(<OtherComponent/>) or  wrapper.find('OtherComponent') ```  tried didn't working out
I am using  tape plus, enzyme for testing.

**Comment by DragorWW** [comment]
@raku1089 you can find it only in `document.querySelector()`
