### ISSUE TITLE
Use react-portal for Portal component

### ISSUE THREAD

**Issue by DragorWW** [sunify/react-relative-portal#7]
The library should do one thing.
Can you replace  [src/Portal.js](https://github.com/smartprogress/react-relative-portal/blob/master/src/Portal.js) on [react-portal](https://github.com/tajo/react-portal) ?

**Comment by DragorWW** [comment]
or we can replace on `createPortal` from React https://github.com/tajo/react-portal/blob/master/src/Portal.js

**Comment by sunify** [comment]
Yeah, we definitely should use `createPortal`
